import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface AnalysisResult {
    anomalyDetected: boolean;
    confidenceScore: number;
    findings: string;
    severity: 'low' | 'medium' | 'high' | 'none';
    recommendations: string[];
    heatmapAreas?: string[];
    heatmapImage?: string; // Base64 encoded image
    anatomicalRegion?: string;
    visionReport?: string;
    detailedAnalysis?: {
        primaryCondition: string;
        differentialDiagnoses: Array<{ condition: string; probability: number }>;
        affectedOrganSystem: string;
        urgencyLevel: string;
    };
    technicalDetails?: {
        modelType: string;
        processingTime: number;
        fileSize: number;
        analysisMethod: string;
    };
}

interface PatientInfo {
    name: string;
    id?: string;
    age?: number | string;
    gender?: string;
    referringPhysician?: string;
    scanDate?: string;
}

export const generateMedicalReport = (
    analysisResult: AnalysisResult,
    patientInfo: PatientInfo,
    type: 'patient' | 'doctor'
) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 20;

    // --- Helper Functions ---
    const addHeader = () => {
        // Logo Placeholder (Teal Circle)
        doc.setFillColor(45, 212, 191); // Teal-400
        doc.circle(margin + 5, 25, 5, 'F');

        // Title
        doc.setFontSize(22);
        doc.setTextColor(15, 23, 42); // Slate-900
        doc.setFont('helvetica', 'bold');
        doc.text('AuraMed', margin + 15, 28);

        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139); // Slate-500
        doc.setFont('helvetica', 'normal');
        doc.text('AI-Powered Diagnostic Center', margin + 15, 34);

        // Report Meta
        doc.setFontSize(10);
        doc.text(`Report ID: AM-${Date.now().toString().slice(-6)}`, pageWidth - margin, 25, { align: 'right' });
        doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin, 30, { align: 'right' });

        // Confidential Stamp
        doc.setTextColor(220, 38, 38); // Red-600
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.text('CONFIDENTIAL MEDICAL RECORD', pageWidth - margin, 38, { align: 'right' });

        // Divider
        doc.setDrawColor(226, 232, 240); // Slate-200
        doc.line(margin, 45, pageWidth - margin, 45);
    };

    const addFooter = (pageNumber: number) => {
        doc.setDrawColor(226, 232, 240);
        doc.line(margin, pageHeight - 20, pageWidth - margin, pageHeight - 20);

        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184); // Slate-400
        doc.text('Generated by AuraMed AI Diagnostic System. This report is for informational purposes only.', margin, pageHeight - 12);
        doc.text(`Page ${pageNumber}`, pageWidth - margin, pageHeight - 12, { align: 'right' });
    };

    // --- Content Generation ---

    addHeader();

    let yPos = 60;

    // 1. Patient Profile Section
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.text('Patient Profile', margin, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85); // Slate-700
    doc.setFont('helvetica', 'normal');

    const col1X = margin;
    const col2X = pageWidth / 2 + 10;

    doc.text(`Name: ${patientInfo.name}`, col1X, yPos);
    doc.text(`Patient ID: ${patientInfo.id || 'N/A'}`, col2X, yPos);
    yPos += 7;

    doc.text(`Age: ${patientInfo.age || 'N/A'}`, col1X, yPos);
    doc.text(`Gender: ${patientInfo.gender || 'N/A'}`, col2X, yPos);
    yPos += 7;

    doc.text(`Ref. Physician: ${patientInfo.referringPhysician || 'Dr. Sarah Johnson'}`, col1X, yPos);
    doc.text(`Scan Date: ${patientInfo.scanDate || new Date().toLocaleDateString()}`, col2X, yPos);
    yPos += 15;

    // 2. Executive Summary & Visualizations
    doc.setFillColor(241, 245, 249); // Slate-100
    doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 55, 3, 3, 'F');

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Executive Summary', margin + 5, yPos + 10);

    // Status Badge
    const statusColor = analysisResult.anomalyDetected
        ? (analysisResult.severity === 'high' ? [220, 38, 38] : [234, 179, 8]) // Red or Yellow
        : [34, 197, 94]; // Green

    doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.roundedRect(margin + 5, yPos + 15, 4, 12, 1, 1, 'F');

    doc.setFontSize(14);
    doc.text(analysisResult.anomalyDetected ? 'Anomaly Detected' : 'Normal Scan', margin + 15, yPos + 22);

    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.setFont('helvetica', 'normal');

    // Confidence Bar Chart
    doc.text(`AI Confidence: ${analysisResult.confidenceScore}%`, margin + 15, yPos + 32);

    // Draw Bar Background
    doc.setFillColor(226, 232, 240);
    doc.roundedRect(margin + 15, yPos + 35, 100, 4, 1, 1, 'F');

    // Draw Bar Fill
    doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.roundedRect(margin + 15, yPos + 35, analysisResult.confidenceScore, 4, 1, 1, 'F');

    if (analysisResult.anomalyDetected) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
        doc.text(`Severity: ${analysisResult.severity.toUpperCase()}`, pageWidth - margin - 50, yPos + 22);
    }

    yPos += 65;

    // 3. Radiological Characteristics & AI Insights
    if (analysisResult.anomalyDetected) {
        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.text('Radiological & AI Analysis', margin, yPos);
        yPos += 5;

        // Heatmap Image Embedding (Left Side)
        let characteristicsStartY = yPos;
        if (analysisResult.heatmapImage) {
            try {
                const imgWidth = 60;
                const imgHeight = 60;
                doc.addImage(analysisResult.heatmapImage, 'PNG', margin, yPos, imgWidth, imgHeight);
                doc.setFontSize(8);
                doc.setTextColor(100, 116, 139);
                doc.text('Anomaly Localization (Heatmap)', margin, yPos + imgHeight + 5);
                characteristicsStartY = yPos; // Keep Y aligned
            } catch (e) {
                console.error("Failed to add heatmap image to PDF", e);
            }
        }

        // Characteristics Table (Right Side)
        const characteristicsData = [
            ['Neuro-Anatomical Region', analysisResult.anatomicalRegion || 'Locating...'], // Uses the new Geometric Fallback
            ['Primary Suspected Condition', analysisResult.detailedAnalysis?.primaryCondition || 'Under Investigation'],
            ['Urgency Level', analysisResult.detailedAnalysis?.urgencyLevel || 'Routine'],
            ['Affected System', analysisResult.detailedAnalysis?.affectedOrganSystem || 'N/A']
        ];

        // @ts-ignore
        autoTable(doc, {
            startY: characteristicsStartY,
            head: [['Diagnostic Metric', 'AI Finding']],
            body: characteristicsData,
            theme: 'grid',
            headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold' }, // Slate-800
            styles: { fontSize: 10, cellPadding: 3 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
            margin: { left: analysisResult.heatmapImage ? margin + 70 : margin, right: margin },
            tableWidth: analysisResult.heatmapImage ? pageWidth - (margin * 2) - 70 : undefined
        });

        // @ts-ignore
        yPos = Math.max(doc.lastAutoTable.finalY + 15, yPos + 70);
    } else {
        yPos += 10;
    }

    // 4. Detailed Findings (Narrative)
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.text('Clinical Findings', margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.setFont('helvetica', 'normal');

    // Clinical Findings Block
    const findings = doc.splitTextToSize(analysisResult.findings, pageWidth - (margin * 2));
    doc.text(findings, margin, yPos);
    yPos += (findings.length * 5) + 10;

    // AI Vision Report (Llava) - NEW SECTION
    if (analysisResult.visionReport) {
        doc.setFillColor(248, 250, 252); // Slate-50 make it subtle
        doc.setDrawColor(226, 232, 240);
        doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 35, 2, 2, 'FD');

        doc.setFontSize(11);
        doc.setTextColor(79, 70, 229); // Indigo-600
        doc.setFont('helvetica', 'bold');
        doc.text('AI Radiologist Note (Vision Model)', margin + 5, yPos + 8);

        doc.setFontSize(9);
        doc.setTextColor(71, 85, 105);
        doc.setFont('helvetica', 'italic');
        const visionText = doc.splitTextToSize(`"${analysisResult.visionReport}"`, pageWidth - (margin * 2) - 10);
        doc.text(visionText, margin + 5, yPos + 16);
        yPos += 45;
    }

    // 5. Differential Diagnosis (Doctor Only)
    if (type === 'doctor' && analysisResult.detailedAnalysis?.differentialDiagnoses) {
        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'bold');
        doc.text('Differential Diagnosis', margin, yPos);
        yPos += 5;

        const tableData = analysisResult.detailedAnalysis.differentialDiagnoses.map(d => [
            d.condition,
            `${d.probability}%`
        ]);

        // @ts-ignore
        autoTable(doc, {
            startY: yPos,
            head: [['Condition', 'Probability']],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [15, 23, 42] },
            margin: { left: margin, right: margin },
        });

        // @ts-ignore
        yPos = doc.lastAutoTable.finalY + 15;
    }

    // 6. Recommendations
    if (yPos > pageHeight - 60) { doc.addPage(); yPos = 40; } // Page break check

    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations', margin, yPos);
    yPos += 10;

    analysisResult.recommendations.forEach((rec) => {
        doc.setFillColor(45, 212, 191);
        doc.circle(margin + 2, yPos - 1, 1, 'F');

        doc.setFontSize(10);
        doc.setTextColor(51, 65, 85);
        doc.setFont('helvetica', 'normal');
        doc.text(rec, margin + 8, yPos);
        yPos += 7;
    });

    // 7. Footer & Interactive Link
    addFooter(doc.getNumberOfPages());

    // Interactive Link to Portal
    doc.setFontSize(9);
    doc.setTextColor(37, 99, 235); // Blue-600
    doc.textWithLink('View Full Interactive Report Online', pageWidth - margin - 60, pageHeight - 20, { url: 'http://localhost:3000/doctor/dashboard' });

    // Save
    const fileName = `AuraMed_Report_${patientInfo.name.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
    doc.save(fileName);
};
